
const content = [
    { type: 'text', text: '¡Hola! Soy Ágata Puig.' },
    { type: 'text', text: 'Mientras todo el mundo crea contenido, muy pocos saben crear pertenencia.' },
    { type: 'text', text: '¿Te has fijado?' },
    { type: 'text', text: 'El Experto Universitario en Dinamización Digital y Social es algo distinto.' },
    { type: 'text', text: 'Te enseño el método completo para que cualquier grupo avance y consiga resultados reales.' },
    { type: 'text', text: 'Es para formadores, coaches, mentores y profesionales que buscan el siguiente nivel.' },
    { type: 'text', text: 'Y estamos listos para encontrarlo contigo.' },
    { type: 'hero-extra', text: 'Es una titulación oficial reconocida en toda Europa.' },
    { type: 'hero-extra', text: 'Equivale a 30 créditos universitarios (ECTS), que es un montón de aprendizaje.' },
    { type: 'hero-extra', text: 'Nos avalan universidades de España, Estados Unidos y México.' },
    { type: 'hero-extra', text: 'Y aprenderás de 20 de los mejores expertos del sector.' },
    { type: 'cta', text: 'Quiero solicitar mi plaza', url: 'https://calendar.app.google/QQqVbyAjwzmUYzNcA' },
    { type: 'text', text: 'Las plazas están limitadas a 30 alumnos, porque nos gusta cuidar a cada uno.' },
    { type: 'testimonial-start', author: 'Isabel', text: 'Con Ágata nunca te sientes sola, siempre tienes apoyo y cercanía.' },
    { type: 'testimonial-story', text: 'Isabel veía el mundo digital frío, pero ahora le pone una humanidad increíble a su profesión sanitaria.' },
    { type: 'text', text: '¿Tus alumnos abandonan tus formaciones?' },
    { type: 'text', text: '¿Te sientes atrapado en un techo de ingresos ofreciendo servicios básicos?' },
    { type: 'text', text: 'Tu problema no es el algoritmo, es la falta de conexión humana real.' },
    { type: 'text', text: 'Si sigues creando más contenido solo para solucionar esto, terminarás agotado.' },
    { type: 'text', text: 'Empujando un carro que se para en cuanto te tomas tres días libres.' },
    { type: 'text', text: 'O siendo reemplazable por la Inteligencia Artificial.' },
    { type: 'text', text: 'La clave es dominar la Inteligencia Relacional.' },
    { type: 'text', text: 'Aprenderás la psicología de grupos para transformar audiencias pasivas en ecosistemas vivos.' },
    { type: 'text', text: 'Podrás escalar tu negocio con una tribu que se sostiene sola.' },
    { type: 'text', text: 'O ser el Arquitecto de Comunidades que las grandes marcas buscan.' },
    { type: 'text', text: '¿Qué porcentaje de alumnos termina realmente una formación hoy?' },
    { type: 'text', text: 'No tienes que responder en voz alta.' },
    { type: 'text', text: 'Si la cifra te incomoda, quédate aquí.' },
    { type: 'text', text: 'Porque esto cambia las reglas del juego.' },
    { type: 'text', text: 'No es culpa del contenido, ni del precio, ni de tus alumnos.' },
    { type: 'text', text: 'Es que nadie te enseñó a diseñar la experiencia que hace que la gente se quede.' },
    { type: 'text', text: 'Piensa en tu semana típica...' },
    { type: 'text', text: 'Grupos de Whatsapp mudos.' },
    { type: 'text', text: 'Módulos que se acumulan sin abrir.' },
    { type: 'text', text: 'Lanzamientos constantes para tapar las bajas.' },
    { type: 'text', text: 'Si tú no estás, todo se para.' },
    { type: 'text', text: 'Te dijeron que el problema era el embudo o el algoritmo.' },
    { type: 'text', text: 'Pero el techo sigue ahí.' },
    { type: 'text', text: 'Sin alumnos que terminen, no hay transformaciones reales.' },
    { type: 'text', text: 'Sin transformaciones, no hay casos de éxito.' },
    { type: 'text', text: 'Y sin casos de éxito, cada vez cuesta más vender.' },
    { type: 'text', text: 'Rompamos ese círculo juntos.' },
    { type: 'testimonial-start', author: 'Sara', text: 'Esto cambia tu forma de trabajar y de verte a ti misma.' },
    { type: 'testimonial-story', text: 'Sara aprendió a valorar su creatividad y a trabajar con mucha menos carga emocional.' },
    { type: 'text', text: 'Quizás tu historia es diferente.' },
    { type: 'text', text: 'Llevas tiempo en redes, pero hay un techo invisible.' },
    { type: 'text', text: 'Lo que más disfrutas es conectar, pero no sabes monetizarlo.' },
    { type: 'text', text: 'Nadie te enseñó a crear pertenencia de forma deliberada.' },
    { type: 'text', text: 'Los expertos en marketing no te cuentan esto:' },
    { type: 'text', text: 'La saturación viene de la soledad disfrazada de comunidad.' },
    { type: 'text', text: 'Grupos llenos de desconocidos.' },
    { type: 'text', text: 'Alumnos que avanzan a oscuras.' },
    { type: 'text', text: 'Formaciones que generan culpa, no resultados.' },
    { type: 'text', text: 'No seas un animador de crucero.' },
    { type: 'text', text: 'No dependas de estar siempre "on".' },
    { type: 'text', text: 'Sin casos de éxito, el mercado ya no te compra promesas.' },
    { type: 'text', text: 'La IA puede montar un temario o escribir un mail...' },
    { type: 'text', text: 'Pero no tiene Inteligencia Relacional.' },
    { type: 'text', text: 'Esa capacidad humana de conectar emocionalmente.' },
    { type: 'text', text: 'Hacer que alguien se sienta visto y parte de algo.' },
    { type: 'text', text: 'La gente no se queda donde consume, se queda donde pertenece.' },
    { type: 'text', text: 'Y eso se puede construir con método.' },
    { type: 'testimonial-start', author: 'Rosalía', text: 'Formarse con Ágata es tener un sello de calidad que te da respaldo.' },
    { type: 'testimonial-story', text: 'Rosalía pasó de la intuición a una estructura clara que le da confianza frente a sus clientes.' },
    { type: 'text', text: 'Mi camino empezó en la trinchera.' },
    { type: 'text', text: 'Aprendí gestionando redes de pequeños restaurantes.' },
    { type: 'text', text: 'Luego, en un programa de salud, vi algo curioso.' },
    { type: 'text', text: 'Con el mismo contenido, los resultados eran distintos.' },
    { type: 'text', text: 'Estudié por qué y descubrí el patrón de activación humana.' },
    { type: 'text', text: 'No era el contenido, era cómo nos activábamos.' },
    { type: 'text', text: 'Se puede aprender. Se puede diseñar.' },
    { type: 'text', text: 'Mis libros son bestsellers porque tengo una tribu viva.' },
    { type: 'text', text: 'Una comunidad que me lleva donde yo sola no llegaría.' },
    { type: 'text', text: 'Esa intuición hoy es un método universitario.' },
    { type: 'image', url: 'https://agatapuig.com/wp-content/uploads/2025/12/WhatsApp-Image-2024-12-02-at-15.36.50-7-e1758534697238-1024x668.jpeg' },
    { type: 'testimonial-start', author: 'Águeda', text: 'Puedes unir la educación con el soporte digital y aplicarlo desde el primer día.' },
    { type: 'testimonial-story', text: 'Águeda integró su pasión por educar en el mundo digital.' },
    { type: 'text', text: 'Grandes del sector ya usan este método.' },
    { type: 'text', text: 'Lector Voraz tiene una comunidad de 1.500 personas activas.' },
    { type: 'text', text: '8Belts redujo el abandono y las devoluciones drásticamente.' },
    { type: 'text', text: 'Crea Tu Huella transformó su participación en identidad propia.' },
    { type: 'text', text: 'Fuertafit y Experienciar dispararon sus tasas de aprovechamiento.' },
    { type: 'testimonial-start', author: 'Ángela', text: 'Me dio una confianza enorme en mi creatividad y en mi proyecto de vida.' },
    { type: 'testimonial-story', text: 'Ángela multiplicó su seguridad y hasta escribió su propio libro.' },
    { type: 'text', text: 'No es un curso de vídeos pregrabados.' },
    { type: 'text', text: 'Es donde aprendes a activar a las personas.' },
    { type: 'text', text: 'Y a convertirlo en una profesión de alta demanda.' },
    { type: 'text', text: 'Con un título que te abre puertas en toda Europa.' },
    { type: 'text', text: 'La formación en sí misma está dinamizada.' },
    { type: 'text', text: 'La vives desde dentro desde el primer día.' },
    { type: 'text', text: 'Mi equipo y yo nos encargamos de que no te quedes a medias.' },
    { type: 'text', text: 'Te dinamizamos a ti mientras aprendes a dinamizar a otros.' },
    { type: 'text', text: 'Dominarás 5 áreas clave:' },
    { type: 'text', text: 'Mentalidad, Dinámicas Sociales, Acompañamiento Humano...' },
    { type: 'text', text: 'Arquitectura de Comunidades y Negocio Dinamizador.' },
    { type: 'text', text: 'He traído a los mayores expertos para conectarte con ellos.' },
    { type: 'text', text: 'Dura 9 meses, con unas 2 o 3 horas de dedicación semanal.' },
    { type: 'text', text: 'Esto te saca del techo donde estás.' },
    { type: 'text', text: 'Si tienes tus propias comunidades, aprenderás a que funcionen solas.' },
    { type: 'text', text: 'Tus alumnos generarán resultados y tus ventas fluirán.' },
    { type: 'text', text: 'Pasarás del modelo de caza al de agricultura: cultivar tierra fértil.' },
    { type: 'text', text: 'Si eres profesional digital, dejarás de ser un proveedor de tareas.' },
    { type: 'text', text: 'Serás el socio estratégico de retención que todos necesitan.' },
    { type: 'text', text: 'Es tu momento de especializarte con título universitario.' },
    { type: 'text', text: 'Y tengo un Compromiso de Empleabilidad contigo.' },
    { type: 'text', text: 'Revisaré tu proyecto personalmente y te daré acceso a mi red.' },
    { type: 'text', text: 'La promesa es que salgas con mercado.' },
    { type: 'testimonial-start', author: 'Nora', text: 'Vivo de esta profesión y he logrado mi mayor sueño.' },
    { type: 'testimonial-story', text: 'Nora, que es médica, ahora diseña comunidades donde sus clientes sanan acompañados.' },
    { type: 'text', text: 'Quiero elegir yo a los próximos alumnos, no su cuenta bancaria.' },
    { type: 'text', text: 'Entras por un proceso de selección para cuidar el grupo.' },
    { type: 'text', text: 'Busco personas que disfruten viendo a otros alcanzar metas.' },
    { type: 'text', text: 'Que crean que la risa y el juego son herramientas serias.' },
    { type: 'text', text: 'Las plazas son solo 30 por edición.' },
    { type: 'text', text: 'Hablemos de la inversión. Sinceramente.' },
    { type: 'text', text: 'Un máster así suele costar una pequeña fortuna.' },
    { type: 'text', text: 'He decidido mantenerlo accesible para que entre el talento.' },
    { type: 'text', text: 'No hay botón de pago. Primero vemos si encajamos.' },
    { type: 'text', text: 'Los negocios que prosperarán son los que saben fidelizar.' },
    { type: 'text', text: 'La dinamización es la solución estratégica hoy.' },
    { type: 'text', text: 'Si esto ha resonado en ti, da el primer paso.' },
    { type: 'cta', text: 'Agenda tu sesión informativa', url: 'https://calendar.app.google/QQqVbyAjwzmUYzNcA' },
    { type: 'text', text: 'Sin compromiso. Hablamos y vemos si es para ti.' }
];
